# use this file to convert/copy any necessary source/data files
# load data ----
library(openxlsx)
shiny_schiz_orig <- read.xlsx('data/STDB_data.xlsx',
                              sheet = 'STDB',
                              fillMergedCells = TRUE)

# edit references subheading
shiny_schiz_orig[1, ncol(shiny_schiz_orig)] <- "References"

taxonomy_syn <- read.xlsx('data/STDB_data.xlsx',
                          sheet = 'Species description history')
colnames(taxonomy_syn) <- gsub(".", " ", colnames(taxonomy_syn), fixed = TRUE)

write.csv(shiny_schiz_orig, "data/STDB.csv", row.names = FALSE)
write.csv(taxonomy_syn, "data/description_history.csv",
          row.names = FALSE)

# copy files to shinylive folder
file.copy("data/STDB.csv", "myapp/data/STDB.csv", overwrite = TRUE)
file.copy("data/description_history.csv", "myapp/data/description_history.csv", overwrite = TRUE)

# copy about and reference HTML ----
file.copy("data/STDB_about.htm", "myapp/data/STDB_about.htm", overwrite = TRUE)
file.copy("data/STDB_references.htm", "myapp/data/STDB_references.htm", overwrite = TRUE)

# copy figure captions ----
tmp <- read.xlsx("data/figure_captions.xlsx", sheet = "Sheet1")
write.csv(tmp, "data/figure_captions.csv", row.names = FALSE)
file.copy("data/figure_captions.csv", "myapp/data/figure_captions.csv", overwrite = TRUE)

# convert figure tiffs to pngs ----
library(tiff)
library(png)

# update PNG files if TIFF files changed
dir.create("docs/drawings_database", recursive = TRUE, showWarnings = FALSE)
tiff_files <- list.files("data/drawings_database", pattern = "\\.tif$")
for (file in tiff_files) {
  src <- file.path("data/drawings_database", file)
  dest <- file.path("docs/drawings_database", sub("\\.tif$", ".png", file))
  if (!file.exists(dest) || file.info(src)$mtime > file.info(dest)$mtime) {
    writePNG(readTIFF(src, native = FALSE), target = dest)
  }
}

# copy R source file ----
src <- readLines("app.R")
start <- which(src == "# ---SHINYLIVE-START---") + 1
header_lines <- c(
  "# Generated by convert_data.R: do not edit by hand.",
  "# Please edit source in app.R",
  "# This file is the source for the shinylive app",
  ""
)
writeLines(c(header_lines, src[start:length(src)]), "myapp/app.R")

# copy included files ----
files <- list.files("www/")
for (file in files) {
  file.copy(paste0("www/", file), paste0("myapp/www/", file), overwrite = TRUE)
}

