# use this file to convert/copy any necessary source/data files
# load data ----
library(openxlsx)
shiny_schiz_orig <- read.xlsx('data/STDB_data.xlsx',
                              sheet = 'STDB',
                              fillMergedCells = TRUE)

# edit references subheading
shiny_schiz_orig[1, ncol(shiny_schiz_orig)] <- "References"

taxonomy_syn <- read.xlsx('data/STDB_data.xlsx',
                          sheet = 'Species description history')
colnames(taxonomy_syn) <- gsub(".", " ", colnames(taxonomy_syn), fixed = TRUE)

write.csv(shiny_schiz_orig, "data/STDB.csv", row.names = FALSE)
write.csv(taxonomy_syn, "data/description_history.csv",
          row.names = FALSE)

# copy files to shinylive folder
file.copy("data/STDB.csv", "myapp/data/STDB.csv", overwrite = TRUE)
file.copy("data/description_history.csv", "myapp/data/description_history.csv", overwrite = TRUE)

# copy about and reference HTML ----
file.copy("data/STDB_about.htm", "myapp/data/STDB_about.htm", overwrite = TRUE)
file.copy("data/STDB_references.htm", "myapp/data/STDB_references.htm", overwrite = TRUE)

# copy figure captions ----
tmp <- read.xlsx("data/figure_captions.xlsx", sheet = "Sheet1")
write.csv(tmp, "data/figure_captions.csv", row.names = FALSE)
file.copy("data/figure_captions.csv", "myapp/data/figure_captions.csv", overwrite = TRUE)

# convert figure tiffs to pngs ----
library(tiff)
library(png)

# remove old files first
file.remove(list.files("docs/drawings_database/", full.names = TRUE))

files <- list.files("data/drawings_database/", "*.tif")
for (file in files) {
  img <- readTIFF(paste0("data/drawings_database/", file), native = FALSE)
  writePNG(img, target = paste0("docs/drawings_database/", gsub(".tif", ".png", file)))
}

# copy R source file ----
tmp <- readLines(file("app.R"))
writeLines(c("# Generated by convert_data.R: do not edit by hand.",
             "# Please edit source in app.R",
             "# This file is the source for the shinylive app",
             "",
             tmp[5:length(tmp)]), file("myapp/app.R"))

# copy included files ----
files <- list.files("www/")
for (file in files) {
  file.copy(paste0("www/", file), paste0("myapp/www/", file), overwrite = TRUE)
}

