# Generated by convert_data.R: do not edit by hand.
# Please edit source in app.R
# This file is the source for the shinylive app

# The Schizomid Trait Database - ShinyApp
# William Gearty and Sandro Pascal Müller
# 2023-09-07

# relevant packages ----
library(shiny)
library(shinyjs)
library(dplyr)
library(DT)
library(janitor)
library(htmltools)
library(fontawesome)
library(prompter)
library(bslib)
library(reactable)

# copied from Hmisc
`%nin%` <- function(x, table) match(x, table, nomatch = 0) == 0

all.is.numeric <- function(x, what = c("test", "vector", "nonnum"), extras = c(".", "NA")) {
  what <- match.arg(what)
  x <- sub("[[:space:]]+$", "", x)
  x <- sub("^[[:space:]]+", "", x)
  xs <- x[x %nin% c("", extras)]
  if (!length(xs) || all(is.na(x))) 
    return(switch(what, test = FALSE, vector = x, nonnum = x[0]))
  isnon <- suppressWarnings(!is.na(xs) & is.na(as.numeric(xs)))
  isnum <- !any(isnon)
  switch(what, test = isnum, vector = if (isnum) suppressWarnings(as.numeric(x)) else x, 
         nonnum = xs[isnon])
}

# load data ----
shiny_schiz_orig <- read.csv("data/STDB.csv", check.names = FALSE)

taxonomy_syn <- read.csv("data/description_history.csv", check.names = FALSE)
colnames(taxonomy_syn) <- gsub(".", " ", colnames(taxonomy_syn), fixed = TRUE)

# convert docx to filtered html, then convert to UTF-8
references_html <- includeHTML("data/STDB_references.htm")
about_html <- includeHTML("data/STDB_about.htm")
body_plan_html <- includeHTML("data/body_plan_caption.htm")

# load figure captions
fig_captions <- read.csv("data/figure_captions.csv")
fig_cols <- fig_captions$Filename

# clean data ----
# make a function to clean strings for use as element ids
idEscape <- function(x) {
  gsub("[^a-zA-Z0-9_]", "_", x)
}

# set up table of headings and subheadings
cols <- data.frame(cat = colnames(shiny_schiz_orig),
                   col = as.character(shiny_schiz_orig[1, ])) %>%
  mutate(cat = gsub(".", " ", cat, fixed = TRUE)) %>%
  mutate(tab = case_when(
    cat %in% c("Family", "Subfamily", "Genus", "Species", "Sex") ~ 1, # Taxonomy and Sex
    cat %in% c("Opisthosoma", "Spermathecae (female)", "Flagellum") ~ 3, # Opisthosoma
    cat %in% c("Size", "Legs") ~ 4, # Legs and Size
    cat %in% c("Ecology", "Distribution") ~ 5,
    grepl("References", cat) ~ 6,
    .default = 2 # Prosoma
  )) %>%
  mutate(col_clean = idEscape(col)) %>% # replace special characters with underscores
  mutate(filt = gsub("(\\s\\(min\\)|\\s\\(max\\))", "", col)) %>%
  mutate(filt_clean = idEscape(filt)) %>%
  mutate(dupe = duplicated(filt))

shiny_schiz <- shiny_schiz_orig %>%
  row_to_names(1) %>%
  arrange(Family, Subfamily, Genus, Species, Sex) %>%
  mutate(across(where(is.character), ~na_if(., "")))

# Find numeric columns
shiny_schiz_clean <- shiny_schiz
shiny_schiz_clean[shiny_schiz == "No data"] <- ""
num_cols <- apply(shiny_schiz_clean, 2, all.is.numeric)

# Round and save numeric values
shiny_schiz[, num_cols] <- round(apply(shiny_schiz_clean[, num_cols], 2, all.is.numeric, what = "vector"),
                                 digits = 2)

# Get male and female columns
male_names <- Reduce(union,
                     list(
                       grep("(male", cols$col, fixed = TRUE, value = TRUE),
                       cols$col[grepl("(male", cols$cat, fixed = TRUE)],
                       grep("(male", cols$cat, fixed = TRUE, value = TRUE)
                     ))
female_names <- Reduce(union,
                       list(
                         grep("(female", cols$col, fixed = TRUE, value = TRUE),
                         cols$col[grepl("(female", cols$cat, fixed = TRUE)],
                         grep("(female", cols$cat, fixed = TRUE, value = TRUE)
                       ))

# table layout and formatting ----
# generate table layout
ref_col <- grep("References", cols$cat)
double_row <- which(cols$cat == cols$col)
col_width <- table(cols$cat)[unique(cols$cat[-double_row])]
tab_layout <- withTags(table(
  class = 'display',
  thead(
    tr(
      lapply(cols$cat[double_row[double_row != ref_col]], function(cat) {
        args <- list(cat, rowspan = 2)
        if(cat == "Sex") {
          args$id <- paste0(cat, "-th")
          args$style <- "cursor: pointer;"
        }
        do.call(th, args)
      }),
      lapply(seq_along(col_width), function(i) {
        th(names(col_width)[i], colspan = col_width[i], style = "text-align: center;")
      }),
      th(cols$cat[ref_col], rowspan = 2)
    ),
    tr(
      lapply((1:nrow(cols))[-double_row], function(i) {
        th(cols$col[i], id = paste0(cols$col_clean[i], "-th"),
           style = ifelse(i %in% which(cols$col_clean %in% fig_cols),
                          "cursor: pointer;", ""))
      })
    )
  )
))

# for formatting NAs
# based on https://stackoverflow.com/a/58526580/4660582
rowCallback <- c(
  "function(row, data){",
  "  $(row).find('td').each(function (index, td) {",
  "    var $td = $(td);",
  "    if ($td.html() == '') {",
  "      $td.html('NA').css({'color': 'rgb(151,151,151)', 'font-style': 'italic'})",
  "    }",
  "  })",
  "}"
)

# server.R ----
server <- function(input, output, session) {
  proxy2 <- dataTableProxy('table2')
  
  # observers ----
  ## navigation and sub-urls ----
  ## modified from https://github.com/kiegan/wait-thats-shiny
  ## update to sub-page/sub-URL when we move to a new tab from the navbar
  #observeEvent(session$clientData$url_hash, {
  observeEvent(input$currentHash, {
    currentHash <- sub("#", "", input$currentHash)
    if (is.null(input$navbarID) || !is.null(currentHash) && currentHash != input$navbarID) {
      freezeReactiveValue(input, "navbarID")
      nav_select("navbarID", selected = currentHash, session)
    }
  }, priority = 1)

  ## push changes to the sub-URL to the browser history so that back/forward browser buttons work
  observeEvent(input$navbarID, {
    # currentHash <- sub("#", "", session$clientData$url_hash) # might need to wrap this with `utils::URLdecode` if hash contains encoded characters (not the case here)
    currentHash <- sub("#", "", input$currentHash)
    pushQueryString <- paste0("#", input$navbarID)
    if (is.null(currentHash) || currentHash != input$navbarID) {
      freezeReactiveValue(input, "navbarID")
      # if being run locally
      # updateQueryString(pushQueryString, mode = "push", session)
      # if being run as a shinylive app
      runjs(paste0("window.parent.history.pushState(null, null, '", pushQueryString, "')"))
      updateTextInput(session, "currentHash", value = pushQueryString)
    }
  }, priority = 0)

  ## modal popups ----
  ### row selection ----
  # modal popup when selecting a row
  observeEvent(input$show_details, {
    data <- shiny_schiz
    for (i in seq_len(nrow(cols))) {
      input_value <- input[[cols$filt_clean[i]]]
      if (!is.null(input_value)) {
        if (is.numeric(shiny_schiz[[cols$col[i]]])) {
          min_val <- min(shiny_schiz[[cols$col[i]]], na.rm = TRUE)
          max_val <- max(shiny_schiz[[cols$col[i]]], na.rm = TRUE)
          if (input_value[1] > min_val | input_value[2] < max_val) {
            if (input[[paste0(cols$filt_clean[i], "-NAs")]]) {
              data <- data %>%
                filter((!!as.symbol(cols$col[i]) >= input_value[1] & 
                          !!as.symbol(cols$col[i]) <= input_value[2]) |
                         is.na(!!as.symbol(cols$col[i])))
            } else {
              data <- data %>%
                filter(!!as.symbol(cols$col[i]) >= input_value[1],
                       !!as.symbol(cols$col[i]) <= input_value[2])
            }
          }
        } else {
          data <- data %>%
            filter(!!as.symbol(cols$col[i]) %in% input_value)
        }
      }
    }
    modal <- modalDialog(
      tags$table(
        lapply(colnames(data), function(name) {
          tags$tr(tags$th(name), tags$td(data[[name]][input$show_details]))
        })
      ),
      title = paste0(data$Species[input$show_details], " (",
                     data$Sex[input$show_details], ")"),
      size = "l",
      easyClose = TRUE
    )
    # insert dismiss button in the header
    modal$children[[1]]$children[[1]]$children[[1]]$children[[2]] <- modalButton("Dismiss")
    showModal(modal)
  })
  
  ### header selection ----
  # modal popup when clicking on a column header
  lapply(which(cols$col_clean %in% fig_cols), function(i) {
    onclick(paste0(cols$col_clean[i], "-th"),
            {
              modal <- modalDialog(title = cols$filt[i],
                                   div(img(src = paste0("https://williamgearty.com/Schizomida/drawings_database/",
                                                        cols$filt_clean[i], ".png"),
                                           alt = cols$filt[i], style = "max-height: 60vh; max-width: 100%;"),
                                       style = "text-align: -moz-center; text-align: -webkit-center;"),
                                   div(fig_captions$Caption[match(cols$filt_clean[i],
                                                                  fig_captions$Filename)]),
                                   size = "l", easyClose = TRUE)
              # insert dismiss button in the header
              modal$children[[1]]$children[[1]]$children[[1]]$children[[2]] <- modalButton("Dismiss")
              showModal(modal)
            })
  })

  ## show/hide columns ----
  ### table 1 ----
  # monitor checkboxes for table1
  lapply(which(cols$tab %in% 1:5 & !cols$dupe), function(i) {
    observeEvent(
      input[[paste0(cols$filt_clean[i], "-checkbox1")]],
      {
        if (input[[paste0(cols$filt_clean[i], "-checkbox1")]]) {
          for (col in cols$col[which(cols$filt_clean == cols$filt_clean[i])]) {
            runjs(paste0("Reactable.toggleHideColumn('table1', '", col,"', false);"))
          }
        } else {
          for (col in cols$col[which(cols$filt_clean == cols$filt_clean[i])]) {
            runjs(paste0("Reactable.toggleHideColumn('table1', '", col,"', true);"))
          }
        }
        runjs("$('.rt-sticky').css({'position': 'relative', 'left': 'unset'}).removeClass('rt-sticky');
               $('#freeze_btn').removeClass('active');")
        
      },
      ignoreInit = TRUE
    )
  })
  
  #### hide entire tabs of columns ----
  lapply(1:5, function(i) {
    observeEvent(
      input[[paste0("hide_all_", i)]],
      {
        if (input[[paste0("hide_all_", i)]]) {
          lapply(cols$filt_clean[cols$tab == i],
                 function(j) runjs(paste0("$('#", j, "-checkbox1').prop('checked', true).trigger('change');")))
        } else {
          lapply(cols$filt_clean[cols$tab == i],
                 function(j) runjs(paste0("$('#", j, "-checkbox1').prop('checked', false).trigger('change');")))
        }
      },
      ignoreInit = TRUE
    )
  })

  ### table 2 ----
  # update all table2 columns based on checkboxes
  checkbox2_rows <- which(cols$cat %in% c("Family", "Subfamily", "Genus", "Species", "Distribution"))
  update_cols2 <- function() {
    # hide columns in table2
    show_cols <- c()
    hide_cols <- c()
    for (i in checkbox2_rows) {
      if (input[[paste0(cols$filt_clean[i], "-checkbox2")]]) {
        show_cols <- c(show_cols, cols$filt[i])
      } else {
        hide_cols <- c(hide_cols, cols$filt[i])
      }
    }
    if (length(show_cols > 0)) {
      showCols(proxy2,
               unname(sapply(show_cols,
                             function(x) which(x == colnames(taxonomy_syn)) - 1)))
    }
    if (length(hide_cols > 0)) {
      hideCols(proxy2,
               unname(sapply(hide_cols,
                             function(x) which(x == colnames(taxonomy_syn)) - 1)))
    }
  }

  # monitor checkboxes for table2
  lapply(checkbox2_rows, function(i) {
    observeEvent(input[[paste0(cols$filt_clean[i], "-checkbox2")]],
                 if (input[[paste0(cols$filt_clean[i], "-checkbox2")]]) {
                   showCols(proxy2, which(cols$filt[i] == colnames(taxonomy_syn)) - 1)
                 } else {
                   hideCols(proxy2, which(cols$filt[i] == colnames(taxonomy_syn)) - 1)
                 },
                 ignoreInit = TRUE
    )
  })
  
  ## numeric filters ----
  # monitor numeric filters and show/hide NA checkboxes when not default
  observeEvent(
    lapply(
      cols$filt_clean[num_cols & !cols$dupe],
      function(name) {
        input[[name]]
      }
    ),
    for(i in which(num_cols & !cols$dupe)) {
      input_value <- input[[cols$filt_clean[i]]]
      ids <- paste0(cols$filt_clean[i], c("-NAs", "-NAs-label"))
      min_val <- min(shiny_schiz[[cols$col[i]]], na.rm = TRUE)
      max_val <- max(shiny_schiz[[cols$col[i]]], na.rm = TRUE)
      if (input_value[1] > min_val | input_value[2] < max_val) {
        sapply(ids, function(id) runjs(paste0("$('#", id, "').show()")))
      } else {
        sapply(ids, function(id) runjs(paste0("$('#", id, "').hide().prop('checked', false).trigger('change')")))
      }
    },
    ignoreInit = TRUE
  )
  
  ## reset buttons ----
  # reset all filters if button is pressed
  observeEvent(input$reset_input1, {
    reset("side-panel1")
    runjs("$('input[id$=checkbox1]').prop('checked', true).trigger('change')")
    runjs("$('input[id^=hide_all]').prop('checked', true).trigger('change')")
  })

  observeEvent(input$reset_input2, {
    reset("side-panel2")
    runjs("$('input[id$=checkbox2]').prop('checked', true).trigger('change')")
  })
  
  ## export buttons ----
  ### excel ----
  js_export <- function(format = 'xlsx', empty = FALSE) {
    paste0("
    $('.buttons-collection').prop('disabled', true);
    var $table = $('.dataTables_scrollBody table:visible');
    var nrows = $table.find('tbody tr').length;
    var instance = $table.tableExport({
      formats: ['", format, "'],
      filename: 'schizomida", ifelse(empty, "_empty", ""), "',
      sheetname: 'Sheet1',
      ignoreRows: ", ifelse(empty, "Array(nrows).fill().map((v,i)=>i)", "null"), "
    });
    $('.export-type-", format, "').click();
    $('.tableexport-caption').remove();
    // var exportData0 = instance.getExportData();
    // var exportData = exportData0[Object.keys(exportData0)[0]]['", format, "'];
    // instance.export2file(exportData.data, exportData.mimeType, exportData.filename, 
    //                      exportData.fileExtension, exportData.merges, 
    //                      exportData.RTL, exportData.sheetname);
    $('.buttons-collection').prop('disabled', false);
    ")
  }
  # trigger excel file download
  observeEvent(input$downloadExcel, {
    runjs(js_export())
  })
  
  ### csv ----
  # trigger csv file download
  observeEvent(input$downloadCSV, {
    runjs(js_export("csv"))
  })
  
  ### empty excel ----
  # trigger empty excel file download
  observeEvent(input$downloadEmptyExcel, {
    runjs(js_export(empty = TRUE))
  })
  
  ## taxonomy filters ----
  ### table 1 ----
  # update subfamily if family is changed
  observeEvent(list(input$Family), {
    dat <- shiny_schiz
    if (!is.null(input$Family)) dat <- dat %>% filter(Family %in% input$Family)
    choices <- sort(unique(as.character(dat$Subfamily)))
    updateSelectizeInput(inputId = "Subfamily", choices = choices, server = TRUE)
  }, ignoreNULL = FALSE, ignoreInit = TRUE)

  # update genus if family/subfamily is changed
  observeEvent(list(input$Family, input$Subfamily), {
    dat <- shiny_schiz
    if (!is.null(input$Family)) dat <- dat %>% filter(Family %in% input$Family)
    if (!is.null(input$Subfamily)) dat <- dat %>% filter(Subfamily %in% input$Subfamily)
    choices <- sort(unique(as.character(dat$Genus)))
    updateSelectizeInput(inputId = "Genus", choices = choices, server = TRUE)
  }, ignoreNULL = FALSE, ignoreInit = TRUE)

  # update species if family/subfamily/genus is changed
  observeEvent(list(input$Family, input$Subfamily, input$Genus), {
    dat <- shiny_schiz
    if (!is.null(input$Family)) dat <- dat %>% filter(Family %in% input$Family)
    if (!is.null(input$Subfamily)) dat <- dat %>% filter(Subfamily %in% input$Subfamily)
    if (!is.null(input$Genus)) dat <- dat %>% filter(Genus %in% input$Genus)
    choices <- sort(unique(as.character(dat$Species)))
    updateSelectizeInput(inputId = "Species", choices = choices, server = TRUE)
  }, ignoreNULL = FALSE, ignoreInit = TRUE)

  # update sex and character filters if family/subfamily/genus/species is changed
  observeEvent(list(input$Family, input$Subfamily, input$Genus, input$Species), {
    dat <- shiny_schiz
    if (!is.null(input$Family)) dat <- dat %>% filter(Family %in% input$Family)
    if (!is.null(input$Subfamily)) dat <- dat %>% filter(Subfamily %in% input$Subfamily)
    if (!is.null(input$Genus)) dat <- dat %>% filter(Genus %in% input$Genus)
    if (!is.null(input$Species)) dat <- dat %>% filter(Species %in% input$Species)
    choices <- sort(unique(as.character(dat$Sex)))
    updateSelectizeInput(inputId = "Sex", choices = choices, server = TRUE)

    # update other character filters
    for (i in which(cols$tab %in% 2:6 & !cols$dupe & sapply(shiny_schiz, Negate(is.numeric)))) {
      if (!is.numeric(dat[[cols$col[i]]])) {
        choices <- sort(unique(as.character(dat[[cols$filt[i]]])))
        updateSelectizeInput(inputId = cols$filt_clean[i], choices = choices,
                             selected = input[[cols$filt_clean[i]]], server = TRUE)
      }
    }
  }, ignoreNULL = FALSE, ignoreInit = TRUE)
  
  ### table 2 ----
  observeEvent(list(input$Family2), {
    dat <- taxonomy_syn
    if (!is.null(input$Family2)) dat <- dat %>% filter(Family %in% input$Family2)
    choices <- sort(unique(as.character(taxonomy_syn$Subfamily)))
    updateSelectizeInput(inputId = "Subfamily2", choices = choices, server = TRUE)
  }, ignoreNULL = FALSE, ignoreInit = TRUE)
  
  # update genus if family/subfamily is changed
  observeEvent(list(input$Family2, input$Subfamily2), {
    dat <- taxonomy_syn
    if (!is.null(input$Family2)) dat <- dat %>% filter(Family %in% input$Family2)
    if (!is.null(input$Subfamily2)) dat <- dat %>% filter(Subfamily %in% input$Subfamily2)
    choices <- sort(unique(as.character(dat$Genus)))
    updateSelectizeInput(inputId = "Genus2", choices = choices, server = TRUE)
  }, ignoreNULL = FALSE, ignoreInit = TRUE)
  
  # update species if family/subfamily/genus is changed
  observeEvent(list(input$Family2, input$Subfamily2, input$Genus2), {
    dat <- taxonomy_syn
    if (!is.null(input$Family2)) dat <- dat %>% filter(Family %in% input$Family2)
    if (!is.null(input$Subfamily2)) dat <- dat %>% filter(Subfamily %in% input$Subfamily2)
    if (!is.null(input$Genus2)) dat <- dat %>% filter(Genus %in% input$Genus2)
    choices <- sort(unique(as.character(dat$Species)))
    updateSelectizeInput(inputId = "Species2", choices = choices, server = TRUE)
  }, ignoreNULL = FALSE, ignoreInit = TRUE)
  
  ## show/hide filters ----
  # update male/female filters when sex is changed
  observeEvent(input$Sex, {
    sapply(idEscape(male_names), showElement)
    sapply(idEscape(female_names), showElement)
    if (!is.null(input$Sex)) {
      if (! "male" %in% input$Sex) {
        sapply(idEscape(male_names), hideElement)
      }
      if (! "female" %in% input$Sex) {
        sapply(idEscape(female_names), hideElement)
      }
    }
  }, ignoreNULL = FALSE, ignoreInit = TRUE)
  
  # datatables ----
  ## data table ----
  ### setup reactive data ----
  values <- reactiveValues(data = shiny_schiz)

  update_others <- TRUE
  update_data <- function(filter_name) {
    data <- shiny_schiz
    for (i in seq_len(nrow(cols))) {
      input_value <- input[[cols$filt_clean[i]]]
      if (!is.null(input_value)) {
        if (is.numeric(shiny_schiz[[cols$col[i]]])) {
          min_val <- min(shiny_schiz[[cols$col[i]]], na.rm = TRUE)
          max_val <- max(shiny_schiz[[cols$col[i]]], na.rm = TRUE)
          if (input_value[1] > min_val | input_value[2] < max_val) {
            if (input[[paste0(cols$filt_clean[i], "-NAs")]]) {
              data <- data %>%
                filter((!!as.symbol(cols$col[i]) >= input_value[1] & 
                          !!as.symbol(cols$col[i]) <= input_value[2]) |
                         is.na(!!as.symbol(cols$col[i])))
            } else {
              data <- data %>%
                filter(!!as.symbol(cols$col[i]) >= input_value[1],
                       !!as.symbol(cols$col[i]) <= input_value[2])
            }
          }
        } else {
          data <- data %>%
            filter(!!as.symbol(cols$col[i]) %in% input_value)
        }
      }
    }
    values$data <- data
  }
  
  lapply(unique(cols$filt_clean), function(filt) {
    observeEvent(input[[filt]], update_data(filt),
                 ignoreNULL = FALSE, ignoreInit = TRUE)
  })
  
  lapply(unique(cols$filt_clean), function(filt) {
    observeEvent(input[[paste0(filt, "-NAs")]], update_data(filt),
                 ignoreNULL = FALSE, ignoreInit = TRUE)
  })

  ### render table ----
  #### reactable ----
  output$table1 <- renderReactable({
    data <- values$data
    # update unique species count
    runjs(paste0("$('#species_count').html('(", length(unique(data$Species)), " unique species)')"))
    runjs("$('#freeze_btn').removeClass('active');")
    reactable(data,
              columns = setNames(lapply(seq_len(nrow(cols)), function(i) {
                colDef(cols$col[i],
                       show = case_when(
                         is.null(input$Sex) ~ TRUE,
                         !("male" %in% input$Sex) && cols$col[i] %in% male_names ~ FALSE,
                         !("female" %in% input$Sex) && cols$col[i] %in% female_names ~ FALSE
                       ),
                       #show = input[[paste0(cols$filt_clean[i], "-checkbox1")]],
                       header = ifelse(
                         cols$col_clean[i] %in% fig_captions$Filename,
                         function(name) {
                           div(
                             div(name, style = "margin-bottom: .5em;"),
                             tags$button("Show figure",
                                         id = paste0(cols$col_clean[i], "-th"),
                                         class = "btn btn-sm btn-secondary",
                                         onclick = "event.stopPropagation();"),
                             class = "rt-text-content"
                           )},
                         function(name) div(name, class = "rt-text-content")
                       )
                )
              }), cols$col),
              defaultColDef = colDef(width = 200, html = TRUE,
                                     na = as.character(span(tags$i("NA"), style = "color: rgb(151,151,151);")),
                                     headerStyle = "cursor: pointer;"),
              columnGroups = lapply(unique(cols$cat[-double_row]), function(cat) {
                  colGroup(name = cat, columns = cols$col[cols$cat == cat])
                }),
              sortable = TRUE,
              showSortable = TRUE,
              onClick = JS("function(rowInfo, column) {
                // Send the click event to Shiny, which will be available in input$show_details
                // Note that the row index starts at 0 in JavaScript, so we add 1
                Shiny.setInputValue('show_details', rowInfo.index + 1, { priority: 'event' })
              }"),
              highlight = TRUE,
              bordered = TRUE,
              striped = TRUE,
              searchable = TRUE,
              pagination = TRUE,
              showPageSizeOptions = TRUE,
              defaultPageSize = 100,
              pageSizeOptions = c(50, 100, 250, 1000),
              elementId = "table1"
    )
  })
  
  ## tax. and syn. table ----
  ### setup reactive data ----
  df2_cols <- which(cols$cat %in% c("Family", "Subfamily", "Genus", "Species", "Distribution"))
  df2 <- eventReactive(
    lapply(
      cols$filt_clean[df2_cols],
      function(name) {
        input[[paste0(name, "2")]]
      }
    ),
    {
      data2 <- taxonomy_syn
      for (col in df2_cols) {
        input_value <- input[[paste0(cols$filt_clean[col], "2")]]
        if (!is.null(input_value)) {
          data2 <- data2 %>%
            filter(!!as.symbol(cols$col[col]) %in% input_value)
        }
      }
      data2
    })

  ### render table ----
  # lots of options available: https://datatables.net/reference/option/
  output$table2 <- DT::renderDataTable(DT::datatable(
    df2(),
    elementId = 'table2',
    rownames = FALSE,
    style = 'bootstrap',
    class = 'table-bordered stripe',
    selection = 'none',
    extensions = 'Buttons',
    options = list(
      scrollX = TRUE,
      scrollY = TRUE,
      scrollCollapse = TRUE,
      paging = FALSE,
      dom = 'Bfrti',
      buttons = list(
        list(extend = "copy", text = paste(fa("clipboard"),  "Copy"),
             exportOptions = list(columns = ":visible"),
             className = "hint--bottom-right hint--rounded hint--info",
             attr = list("aria-label" = "Copy the below table to the clipboard")),
        list(extend = "collection", text = paste(fa("download", prefer_type = "solid"), "CSV"),
             action = JS("function ( e, dt, node, config ) {
                                 Shiny.setInputValue('downloadCSV', true, {priority: 'event'});
                               }"),
             className = "hint--bottom-right hint--rounded hint--info",
             attr = list("aria-label" = "Download a copy of the below table in CSV format")
        ),
        list(extend = "collection", text = paste(fa("download", prefer_type = "solid"), "Excel"),
             action = JS("function ( e, dt, node, config ) {
                                 Shiny.setInputValue('downloadExcel', true, {priority: 'event'});
                               }"),
             className = "hint--bottom-right hint--rounded hint--info",
             attr = list("aria-label" = "Download a copy of the below table in Excel format")
        )
      ),
      rowCallback = JS(rowCallback), # formatting NAs
      infoCallback = JS(c(
        "function( settings, start, end, max, total, pre ) {",
        "  return 'Showing ' + total + ' species';",
        "}"
      )) # for formatting the info below the table
    )))
  ### update columns ----
  # update columns based on checkboxes
  observeEvent(df2(), update_cols2())
}

# ui.R ----
ui <- {
  page_fillable(
    theme = bs_theme(version = 5, preset="bootstrap"),
    fillable_mobile = TRUE,
    useShinyjs(),
    use_prompt(),
    ## head ----
    tags$head(
      tags$style(
        HTML(
        "body > h2 {
           margin-left: .5rem
         }
         #Genus option, #Genus + div, #Species option, #Species + div {
           font-style: italic;
         }
         .reactable {
           padding-right: var(--_padding);
         }
         div.col-sm-6:has(> div.form-group[style*='display: none']) {
           display: none;
         }
         .dataTables_filter {
           float: right;
         }
         #table2, .dataTables_wrapper, .main {
           padding-right: 0px !important;
         }
         h5 {
           font-style: italic;
         }
         .dataTables_scrollBody {
           max-height: 60vh;
           max-height: 60dvh;
         }
         .tableexport-caption {
           display: none;
         }
         .sidebar-content .card-body {
           height: 80vh !important;
           height: 80dvh !important;
           overflow-y: auto !important;
           overflow-x: hidden !important;
         }
         #side-panel1 {
           z-index: 11;
         }
         .collapse-toggle {
           z-index: 12 !important;
         }
         .darkmode--activated .rt-tr-striped {
           background-color: #e0e0e0 !important;
         }
         .darkmode--activated .table-striped tr.odd>* {
           background-color: #e0e0e0 !important;
         }
         .darkmode-layer, .darkmode-toggle {
           z-index: 500;
         }
         .darkmode--activated .modal-content {
           background-color: black !important;
           color: white !important;
           border: solid white !important;
         }
         .darkmode--activated .modal-content img {
           filter: invert(100%);
         }
         .sidebar-content {
           padding: 0 !important;
         }
         .accordion-item:nth-of-type(1) .accordion-header,
         .accordion-item:nth-of-type(1) .accordion-button {
           background-color: #aaffb1;
         }
         .accordion-item:nth-of-type(2) .accordion-header,
         .accordion-item:nth-of-type(2) .accordion-button {
           background-color: #ffd0d0;
         }
         .accordion-item:nth-of-type(3) .accordion-header,
         .accordion-item:nth-of-type(3) .accordion-button {
           background-color: #ffdfa5;
         }
         .accordion-item:nth-of-type(4) .accordion-header,
         .accordion-item:nth-of-type(4) .accordion-button {
           background-color: #ffc0ff;
         }
         .accordion-item:nth-of-type(5) .accordion-header,
         .accordion-item:nth-of-type(5) .accordion-button {
           background-color: #ccccff;
         }
         .accordion-title {
           font-size: large !important;
         }
         .nav li a {
           margin-right: 10px !important;
           font-size: large !important;
         }
         "
        ),
      ),
      tags$script(src = "xlsx.core.min.js"),
      tags$script(src = "FileSaver.min.js"),
      tags$script(src = "tableexport.min.js"),
      tags$script(src = "https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"),
      tags$script(src = "https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js"),
      tags$script(src = "https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"),
      tags$script(src = "export_excel.js"),
    ),
    # JS for dark mode widget
    tags$script(HTML("function addDarkmodeWidget() {
        new Darkmode({label: '🌓', left: '32px', right: 'unset'}).showWidget();
      }
      window.addEventListener('load', addDarkmodeWidget);
      $(function() {
        $('.navbar-collapse').append($(\"<a href='https://github.com/willgearty/Schizomida/issues' target='_blank' class='btn btn-primary'>Contribute</a>\"));
      });"
    )),
    # hacky JS/HTML for handling back/forward button
    tags$script(HTML("$(function() {
        $(window.parent).on('hashchange', function (e) {
          $('#currentHash').val(window.parent.location.hash).change();
        });
      });"
    )),
    hidden(textInput("currentHash", NULL, value = "#database")),
    ## title ----
    titlePanel('Schizomida Trait Data Base (STDB)'),
    ## panels ----
    page_navbar(theme = bs_theme(version = 5, preset="bootstrap"),
      bg = "#f7f6f4", gap = "0px", id = "navbarID", selected = "database",
      ### reactable database ----
      nav_panel("Database", value = "database", layout_sidebar(
        div(div(tags$button(HTML(paste(fa("download", prefer_type = "solid"), "Download Data")),
                        class = "btn btn-default dropdown-toggle",
                        type = "button", "data-bs-toggle" = "dropdown", "aria-haspopup" = "true",
                        "aria-expanded" = "false"),
            tags$ul(
              tags$li(tags$button(HTML(paste(fa("clipboard"), "Copy to Clipboard")),
                                              class="btn btn-default dropdown-item",
                                  onclick = JS("var tmp = $('.rt-tr-header .rt-th').map(function() {
                                                            return this.getAttribute('aria-label').replace('Sort ', '');
                                                          }).toArray()
                                                navigator.clipboard.writeText(Reactable.getDataCSV('table1', {columnIds: tmp, sep: '\t'}));
                                                alert('Copied the table to the clipboard');")) %>%
                        tooltip("Copy the below table to the clipboard")),
              tags$li(tags$button(HTML(paste(fa("file-csv", prefer_type = "solid"), "Download CSV")),
                                  onclick = JS("var tmp = $('.rt-tr-header .rt-th').map(function() {
                                                            return this.getAttribute('aria-label').replace('Sort ', '');
                                                          }).toArray()
                                                Reactable.downloadDataCSV('table1', 'STDB.csv', {columnIds: tmp})"),
                                  class="btn btn-default dropdown-item") %>%
                        tooltip("Download a copy of the below table in CSV format")),
              tags$li(tags$button(HTML(paste(fa("file-excel", prefer_type = "solid"), "Download Excel")),
                                  onclick = JS("exportExcel('table1', 'STDB.xlsx')"),
                                  class="btn btn-default dropdown-item") %>%
                        tooltip("Download an empty copy of the below table in Excel format")),
              tags$li(tags$button(HTML(paste(fa("file-excel"), "Download Empty Excel")),
                                  onclick = JS("exportExcel('table1', 'STDB_empty.xlsx', true)"),
                                  class="btn btn-default dropdown-item") %>%
                        tooltip("Download an empty copy of the below table in Excel format (only colomn headers)")),
              class="dropdown-menu"),
            class = "btn-group", role="group"),
            tags$button("Freeze First Column", id = "freeze_btn", class = "btn btn-default",
                        onclick = JS("
                        var sticky = $('.rt-sticky').length > 0;
                        if (sticky) {
                          $('.rt-sticky').css({'position': 'relative', 'left': 'unset'}).removeClass('rt-sticky');
                          $('.rt-tr-striped-sticky').addClass('rt-tr-striped').removeClass('rt-tr-striped-sticky');
                          $('.rt-tr-highlight-sticky').addClass('rt-tr-highlight').removeClass('rt-tr-highlight-sticky');
                          $('#freeze_btn').removeClass('active');
                        } else {
                          $('.rt-tr:not(.rt-tr-group-header').find('div:first').css({'position': 'sticky', 'left': '0px'}).addClass('rt-sticky');
                          $('.rt-tr-striped').removeClass('rt-tr-striped').addClass('rt-tr-striped-sticky');
                          $('.rt-tr-highlight').removeClass('rt-tr-highlight').addClass('rt-tr-highlight-sticky');
                          $('#freeze_btn').addClass('active');
                        }")) %>%
              tooltip("Freeze the first currently visible column", class = "btn btn-default", style = "padding: 0;"),
            class = "btn-group", role="group",
            style = "position: absolute; top: var(--bslib-mb-space); z-index: 10;"),
        reactableOutput("table1"),
        div(
          div(paste0("(", length(unique(shiny_schiz$Species)), " unique species)"),
              id = "species_count", style = "margin-right: auto;"),
          div("Click a row for a species summary",
              style = "margin-right: var(--bslib-mb-spacer); text-align: right;"),
          style = "display: flex; margin-top: calc(-1 * var(--bslib-mb-spacer));"
          ),
        #### filters ----
        sidebar = sidebar(width = "35%",
                          card(fluidRow(h4("Filters"),
                                        accordion(id = "database-accordion",
                                                  multiple = FALSE,
                                                  accordion_panel(
                                                    HTML(paste0("Taxonomy and Sex ",
                                                                span(HTML("<input type='checkbox' checked id='hide_all_1' ",
                                                                          "data-bs-toggle='collapse' data-bs-target>")) %>%
                                                                  tooltip("show/hide this entire section of columns"))),
                                                    value = "1",
                                                    fluidRow(lapply(seq_len(cols %>% filter(tab == 1) %>% nrow()), function(i) {
                                                      column(4,
                                                             selectizeInput(inputId = cols$col_clean[i],
                                                                         label = HTML(paste0(cols$col[i],
                                                                                             " <input type = 'checkbox' checked id = ",
                                                                                             "'", cols$col_clean[i], "-checkbox1'>")) %>%
                                                                           tooltip("show/hide this column"),
                                                                         choices = sort(unique(as.character(shiny_schiz[[cols$col[i]]]))),
                                                                         multiple = TRUE))
                                                    }))
                                                  ),
                                                  accordion_panel(
                                                    HTML(paste0("Prosoma ",
                                                                span(HTML("<input type='checkbox' checked id='hide_all_2' ",
                                                                          "data-bs-toggle='collapse' data-bs-target>")) %>%
                                                                  tooltip("show/hide this entire section of columns"))),
                                                    value = "2",
                                                    lapply(unique(cols$cat[cols$tab == 2]), function(cat_name) {
                                                      cols_sub <- cols %>% filter(cat == cat_name, !dupe)
                                                      list(fluidRow(column(12, h5(cat_name, id = idEscape(cat_name)))),
                                                           fluidRow(lapply(seq_len(nrow(cols_sub)), function(i) {
                                                             if (is.numeric(shiny_schiz[[cols_sub$col[i]]])) {
                                                               min_val <- min(shiny_schiz[[cols_sub$col[i]]], na.rm = TRUE)
                                                               max_val <- max(shiny_schiz[[cols_sub$col[i]]], na.rm = TRUE)
                                                               column(6, sliderInput(inputId = cols_sub$filt_clean[i],
                                                                                     label = HTML(paste(cols_sub$filt[i], tooltip(HTML(paste0("<input type = 'checkbox' checked id = ",
                                                                                                                          "'", cols_sub$filt_clean[i], "-checkbox1'>")), "show/hide this column"),
                                                                                                         HTML(paste0("<br><label id='", cols_sub$filt_clean[i], "-NAs-label' ",
                                                                                                         "for='", cols_sub$filt_clean[i], "-NAs' ",
                                                                                                         "style='font-size: small; display: none;'>",
                                                                                                         "Include NAs</label> ",
                                                                                                         "<input style='display: none;' type = 'checkbox' id = '",
                                                                                                         cols_sub$filt_clean[i], "-NAs'>")) %>% tooltip("include NA values in this column"))),
                                                                                     min = min_val,
                                                                                     max = max_val,
                                                                                     value = c(min_val, max_val),
                                                                                     step = .01))
                                                             } else {
                                                               column(6, selectizeInput(inputId = cols_sub$col_clean[i],
                                                                                     label = HTML(paste0(cols_sub$col[i],
                                                                                                         " <input type = 'checkbox' checked id = ",
                                                                                                         "'", cols_sub$col_clean[i], "-checkbox1'>")) %>%
                                                                                       tooltip("show/hide this column"),
                                                                                     choices = sort(unique(as.character(shiny_schiz[[cols_sub$col[i]]]))),
                                                                                     multiple = TRUE))
                                                             }
                                                           })))
                                                    })
                                                  ),
                                                  accordion_panel(
                                                    HTML(paste0("Opisthosoma ",
                                                                span(HTML("<input type='checkbox' checked id='hide_all_3' ",
                                                                          "data-bs-toggle='collapse' data-bs-target>")) %>%
                                                                  tooltip("show/hide this entire section of columns"))),
                                                    value = "3",
                                                    lapply(unique(cols$cat[cols$tab == 3]), function(cat_name) {
                                                      cols_sub <- cols %>% filter(cat == cat_name, !dupe)
                                                      list(fluidRow(column(12, h5(cat_name, id = idEscape(cat_name)))),
                                                           fluidRow(lapply(seq_len(nrow(cols_sub)), function(i) {
                                                             if (is.numeric(shiny_schiz[[cols_sub$col[i]]])) {
                                                               min_val <- min(shiny_schiz[[cols_sub$col[i]]], na.rm = TRUE)
                                                               max_val <- max(shiny_schiz[[cols_sub$col[i]]], na.rm = TRUE)
                                                               column(6, sliderInput(inputId = cols_sub$filt_clean[i],
                                                                                     label = HTML(paste0(cols_sub$filt[i], " ",
                                                                                                         HTML(paste0("<input type = 'checkbox' checked id = ",
                                                                                                         "'", cols_sub$filt_clean[i], "-checkbox1'>")) %>%
                                                                                                           tooltip("show/hide this column"),
                                                                                                         "<br><label id='", cols_sub$filt_clean[i], "-NAs-label' ",
                                                                                                         "for='", cols_sub$filt_clean[i], "-NAs' ",
                                                                                                         "style='font-size: small; display: none;'>",
                                                                                                         "Include NAs</label> ",
                                                                                                         "<input style='display: none;' type = 'checkbox' id = '",
                                                                                                         cols_sub$filt_clean[i], "-NAs'>")),
                                                                                     min = min_val,
                                                                                     max = max_val,
                                                                                     value = c(min_val, max_val),
                                                                                     step = .01))
                                                             } else {
                                                               column(6, selectizeInput(inputId = cols_sub$col_clean[i],
                                                                                     label = HTML(paste0(cols_sub$col[i],
                                                                                                         " <input type = 'checkbox' checked id = ",
                                                                                                         "'", cols_sub$col_clean[i], "-checkbox1'>")) %>%
                                                                                       tooltip("show/hide this column"),
                                                                                     choices = sort(unique(as.character(shiny_schiz[[cols_sub$col[i]]]))),
                                                                                     multiple = TRUE))
                                                             }
                                                           })))
                                                    })
                                                  ),
                                                  accordion_panel(
                                                    HTML(paste0("Legs and Size ",
                                                                span(HTML("<input type='checkbox' checked id='hide_all_4' ",
                                                                          "data-bs-toggle='collapse' data-bs-target>")) %>%
                                                                  tooltip("show/hide this entire section of columns"))),
                                                    value = "4",
                                                    lapply(unique(cols$cat[cols$tab == 4]), function(cat_name) {
                                                      cols_sub <- cols %>% filter(cat == cat_name, !dupe)
                                                      list(fluidRow(column(12, h5(cat_name, id = idEscape(cat_name)))),
                                                           fluidRow(lapply(seq_len(nrow(cols_sub)), function(i) {
                                                             if (is.numeric(shiny_schiz[[cols_sub$col[i]]])) {
                                                               min_val <- min(shiny_schiz[[cols_sub$col[i]]], na.rm = TRUE)
                                                               max_val <- max(shiny_schiz[[cols_sub$col[i]]], na.rm = TRUE)
                                                               column(6, sliderInput(inputId = cols_sub$filt_clean[i],
                                                                                     label = HTML(paste0(cols_sub$filt[i], " ",
                                                                                                         HTML(paste0("<input type = 'checkbox' checked id = ",
                                                                                                         "'", cols_sub$filt_clean[i], "-checkbox1'>")) %>%
                                                                                                           tooltip("show/hide this column"),
                                                                                                         "<br><label id='", cols_sub$filt_clean[i], "-NAs-label' ",
                                                                                                         "for='", cols_sub$filt_clean[i], "-NAs' ",
                                                                                                         "style='font-size: small; display: none;'>",
                                                                                                         "Include NAs</label> ",
                                                                                                         HTML(paste0("<input style='display: none;' type = 'checkbox' id = '",
                                                                                                         cols_sub$filt_clean[i], "-NAs'>")) %>%
                                                                                                           tooltip("include NA values in this column"))),
                                                                                     min = min_val,
                                                                                     max = max_val,
                                                                                     value = c(min_val, max_val),
                                                                                     step = .01))
                                                             } else {
                                                               column(6, selectizeInput(inputId = cols_sub$col_clean[i],
                                                                                     label = HTML(paste0(cols_sub$col[i],
                                                                                                         " <input type = 'checkbox' checked id = ",
                                                                                                         "'", cols_sub$col_clean[i], "-checkbox1'>")) %>%
                                                                                       tooltip("show/hide this column"),
                                                                                     choices = sort(unique(as.character(shiny_schiz[[cols_sub$col[i]]]))),
                                                                                     multiple = TRUE))
                                                             }
                                                           })))
                                                    })
                                                  ),
                                                  accordion_panel(
                                                    HTML(paste0("Ecology and Locality ",
                                                                span(HTML("<input type='checkbox' checked id='hide_all_5' ",
                                                                          "data-bs-toggle='collapse' data-bs-target>")) %>%
                                                                  tooltip("show/hide this entire section of columns"))),
                                                    value = "5",
                                                    lapply(unique(cols$cat[cols$tab == 5]), function(cat_name) {
                                                      cols_sub <- cols %>% filter(cat == cat_name)
                                                      list(fluidRow(column(12, h5(cat_name, id = idEscape(cat_name)))),
                                                           fluidRow(lapply(seq_len(nrow(cols_sub)), function(i) {
                                                             column(6,
                                                                    selectizeInput(inputId = cols_sub$col_clean[i],
                                                                                label = HTML(paste0(cols_sub$col[i],
                                                                                                    " <input type = 'checkbox' checked id = ",
                                                                                                    "'", cols_sub$col_clean[i], "-checkbox1'>")) %>%
                                                                                  tooltip("show/hide this column"),
                                                                                choices = sort(unique(as.character(shiny_schiz[[cols_sub$col[i]]]))),
                                                                                multiple = TRUE))
                                                           })))
                                                    })
                                                  )
                                        )
                          )),
                          #### reset button ----
                          div(style="text-align: center; padding-bottom: var(--bslib-mb-spacer)",
                              add_prompt(actionButton("reset_input1", HTML(paste(fa("rotate", prefer_type = "solid"), "Reset all filters")), width = "50%"),
                                         message = "Reset the table to its original form",
                                         position = "top", rounded = TRUE)),
                          id = "side-panel1"
        )
      )
      ),
      ### species hist. ----
      nav_panel("Species Description History", value = "history", layout_sidebar(
            fluidRow(DT::dataTableOutput('table2'), style = "width: 100%;"),
            #### filters ----
            sidebar = sidebar(width = "35%",
                              card(fluidRow(h4("Filters"),
                                            accordion(multiple = FALSE,
                                                      accordion_panel(
                                                        "Taxonomy",
                                                        fluidRow(lapply(seq_len(cols %>% filter(tab == 1, cat != "Sex") %>% nrow()), function(i) {
                                                          column(4,
                                                                 selectInput(inputId = paste0(cols$col_clean[i], "2"),
                                                                             label = HTML(paste0(cols$col[i],
                                                                                                 " <input type = 'checkbox' checked id = ",
                                                                                                 "'", cols$col_clean[i], "-checkbox2' ",
                                                                                                 "aria-label = 'show/hide this column'",
                                                                                                 "class = '",
                                                                                                 ifelse((i %% 3) == 0, "hint--bottom-left", "hint--bottom-right"),
                                                                                                 " hint--rounded'>")),
                                                                             choices = sort(unique(as.character(taxonomy_syn[[cols$col[i]]]))),
                                                                             multiple = TRUE))
                                                        }))
                                                      ),
                                                      accordion_panel(
                                                        "Locality",
                                                        lapply(unique(cols$cat[cols$cat == "Distribution"]), function(cat_name) {
                                                          cols_sub <- cols %>% filter(cat == cat_name)
                                                          list(fluidRow(column(12, h5(cat_name, id = idEscape(cat_name)))),
                                                               fluidRow(lapply(seq_len(nrow(cols_sub)), function(i) {
                                                                 column(6,
                                                                        selectInput(inputId = paste0(cols_sub$col_clean[i], "2"),
                                                                                    label = HTML(paste0(cols_sub$col[i],
                                                                                                        " <input type = 'checkbox' checked id = ",
                                                                                                        "'", cols_sub$col_clean[i], "-checkbox2' ",
                                                                                                        "aria-label = 'show/hide this column'",
                                                                                                        "class = '",
                                                                                                        ifelse((i %% 2) == 1, "hint--bottom-right", "hint--bottom-left"),
                                                                                                        " hint--rounded'>")),
                                                                                    choices = sort(unique(as.character(taxonomy_syn[[cols_sub$col[i]]]))),
                                                                                    multiple = TRUE))
                                                               })))
                                                        })
                                                      )
                                            )
            )),
            #### reset button ----
            div(style="text-align: center; padding-bottom: var(--bslib-sidebar-padding);",
                add_prompt(actionButton("reset_input2", HTML(paste(fa("rotate", prefer_type = "solid"), "Reset all filters")), width = "50%"),
                           message = "Reset the table to its original form",
                           position = "top", rounded = TRUE)),
            id = "side-panel2"
            )
          )),
      ### general anatomy ----
      nav_panel(
        "Schizomid General Anatomy", value = "anatomy",
        div(img(src = paste0("https://williamgearty.com/Schizomida/drawings_database/body_plan.png"),
                    alt = "Schizomida body plan",
                    style = "max-height: 70vh; max-width: 100%; float: left;"),
            div(body_plan_html),
            style = "overflow-y: scroll; flex: 1 1 auto;")
      ),
      ### references ----
      nav_panel(
            "Full References", value = "references",
            div(references_html, style = "overflow-y: scroll; flex: 1 1 auto;;")
          ),
      ### about ----
      nav_panel(
            "About and Contact", value = "about",
            div(about_html, style = "overflow-y: scroll; flex: 1 1 auto;;")
          )
    )
  )
}

# Run shiny ----
shinyApp(ui = ui, server = server)



